services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # map port 80 (host) to port 80 (container) for http traffic
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Use custom nginx config (bind mount, read only)
    container_name: nginx-reverse-proxy
    depends_on:
      - app
  app:
    build:
      context: .
    image: sparta-test-app
    container_name: sparta-test-app
    ports:
      - "3000:3000"  # Expose Node.js directly (for debugging)
    depends_on:
      mongo_db:
        condition: service_healthy  # Ensure MongoDB is fully ready before app starts
    environment:
      - DB_HOST=mongodb://mongo_db:27017/posts
  mongo_db:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    volumes:
      - mongo_db_data:/data/db  # Persist MongoDB data
    healthcheck:  # Add health check to ensure MongoDB is fully ready before app starts
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"] # Check if MongoDB is responsive
      interval: 10s # Check every 10 seconds
      retries: 5 # Retry 5 times before failing
      start_period: 10s # Wait 10 seconds before starting health checks
  
volumes:
  mongo_db_data:

