apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 100Mi # provision 100mb
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node (my local machine)
  hostPath:
    path: "/var/lib/mongodb"  # Local host (Docker Desktop Kubernetes VM) storage path where the data will be stored
  persistentVolumeReclaimPolicy: Retain # keep PV data even after PVC is deleted
