---
- name: Install app dependencies and run app with pm2
  hosts: web
  become: true

  tasks:

    - name: Add NodeSource repository for Node.js 20.x
      shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      args:
        executable: /bin/bash
        creates: /etc/apt/sources.list.d/nodesource.list  # Ensures NodeSource repo exists

    - name: Upgrade all system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Remove app if already existing
      file:
        path: "/home/ubuntu/tech501-sparta-app"
        state: absent # ensures the path is absent

    - name: Clone or update repository
      git:
        repo: "https://github.com/sameem97/tech501-sparta-app.git"
        dest: "/home/ubuntu/tech501-sparta-app"
        version: "main"
        force: yes

    - name: Install npm dependencies
      command: npm install --loglevel verbose
      args:
        chdir: "/home/ubuntu/tech501-sparta-app/app"

    - name: Stop any running Node.js application
      shell: pm2 delete app || true
      ignore_errors: yes

    - name: Start the Node.js application
      shell: pm2 start app.js --name app --env production --update-env
      args:
        chdir: "/home/ubuntu/tech501-sparta-app/app"

    - name: Ensure PM2 auto-starts on reboot for user 'ubuntu'
      command: pm2 startup systemd -u ubuntu --hp /home/ubuntu
      args:
        creates: /etc/systemd/system/pm2-ubuntu.service  # only run if systemd service not already defined

    - name: Save pm2 process list
      command: pm2 save